#!/bin/bash
# Author: Domas Kalinauskas (lynxcs)
# Application: bico
# Description: Outputs icons depending on battery level and status
#
#
#
static_bat(){
BATC=`cat /sys/class/power_supply/BAT0/capacity`
case $BATC in
	[0-1][0-9])
		BATICO=""
		;;
	[2-3][0-9])
                BATICO=""
                ;;
        [4-5][0-9])
                BATICO=""
                ;;
        [6-7][0-9])
                BATICO=""
                ;;
        [8-9][0-9])
                BATICO=""
                ;;
        100)
                BATICO=""
                ;;
esac

echo "$BATC% $BATICO "
}
charging(){
batteryCounter=1
while true; do

	case $batteryCounter in
        	1)
                	batteryCounter=2
			BATICO=""
	       		;;
        	2)
			batteryCounter=3
                	BATICO=""
			;;
        	3)
			batteryCounter=4
                	BATICO=""
			;;
        	4)
			batteryCounter=5
                	BATICO=""
			;;
        	5)
			batteryCounter=1
                	BATICO=""
			;;
	esac

	echo -n -e "$BATICO"\\r
	sleep 0.35
done
}
#Text modifiers
RED='\033[0;31m'
NC='\033[0m'
#Process arguments
while [[ $# -gt 0 ]]; do

key="$1"
case $key in
	-s|--static)
		if [[ "$CHARGING" -eq "1" ]]; then
			echo -e "$RED!CAN'T USE STATIC (-s) WITH CHARGING (-c)!$NC"
			exit 1
		fi
		STATIC=1
		shift
		;;
        -c|--charging)
		if [[ "$STATIC" -eq "1" ]]; then
			echo -e "$RED!CAN'T USE CHARGING (-c) WITH STATIC (-s)!$NC"
			exit 1
		fi
		CHARGING=1
		shift
		;;
esac
done
#Execute commands.
if [[ "$STATIC" -eq "1" ]]; then
	static_bat;
elif [[ "$CHARGING" -eq "1" ]]; then
	charging;
else #Fallback to automatic (If status=charging then charging else static
	BATS=`cat /sys/class/power_supply/BAT0/status`
	if [ $BATS = "Charging" ]; then
		charging;
	else
	static_bat;
	fi
fi
